sonar.projectKey=eiaiproject_Bagarry
sonar.organization=eiaiproject
sonar.projectName=Bagarry
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/node_modules/**,**/.wrangler/**,**/test-results/**,**/*.test.ts,e2e/**,scripts/**,seed/**,migrations/**
sonar.typescript.tsconfigPath=tsconfig.json
